[workspace]
resolver = "2"
members = [
	"hal",
	"atsamd-hal-macros",
	"pac/*",
	"boards/*",
]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "s"
